CREATE DATABASE OnlineOrders
GO
USE OnlineOrders
GO
CREATE TABLE Customers
(
	CustId INT PRIMARY KEY IDENTITY,
	Fname NVARCHAR(255) NOT NULL,
	Lname NVARCHAR(255) NOT NULL,
	Dob DATE,
	Gender BIT,
	Pno VARCHAR(255),
	[Address] NVARCHAR(255) NOT NULL,
	[Password] VARCHAR(255),
	[Status] TINYINT
);
CREATE TABLE Advertisements
(
	Id  INT PRIMARY KEY IDENTITY,
	[Image] VARCHAR(255) NOT NULL,
	[Key] VARCHAR(255) NOT NULL,
	[Description] TEXT
);
CREATE TABLE Banner
(
	Id  INT PRIMARY KEY IDENTITY,
	[Image] VARCHAR(255) NOT NULL,
	Sort TINYINT,
	[Description] TEXT
);
CREATE TABLE Blog
(
	Id INT PRIMARY KEY IDENTITY,
	Title VARCHAR(255) NOT NULL,
	Summary VARCHAR(255) NOT NULL,
	Content TEXT,
	[Image] VARCHAR(255) NOT NULL,
	[Status] TINYINT,
	[VIEW] INT
);
CREATE TABLE Payments
(
	Id INT PRIMARY KEY IDENTITY,
	Name VARCHAR(255) NOT NULL,
	[Image] VARCHAR(255) DEFAULT NULL,
);
CREATE TABLE Shipping
(
	Id INT PRIMARY KEY IDENTITY,
	Name VARCHAR(255) NOT NULL,
	Price FLOAT NOT NULL,
);
CREATE TABLE Size
(
	Id INT PRIMARY KEY IDENTITY,
	Size VARCHAR(255) NOT NULL,
	Price FLOAT NOT NULL
);
CREATE TABLE Frames
(
	Id INT PRIMARY KEY IDENTITY,
	Frames VARCHAR(255) NOT NULL,
	Price FLOAT NOT NULL
);
CREATE TABLE Orders
(
	Id INT PRIMARY KEY IDENTITY,
	TotalPrice FLOAT NOT NULL,
	CustId INT FOREIGN KEY REFERENCES Customers(CustId),
	OrderNote TEXT,
	TotalQuantity INT NOT NULL,
	PaymentId INT FOREIGN KEY REFERENCES Payments(id),
	ShippingId INT FOREIGN KEY REFERENCES Shipping(id),
	[Status] TINYINT,
	CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
	UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE OrderDetail
(
	Id INT PRIMARY KEY IDENTITY,
	[Image] VARCHAR(255) DEFAULT NULL,
	Price FLOAT NOT NULL,
	SizeId INT FOREIGN KEY REFERENCES Size(Id),
	FramesId INT FOREIGN KEY REFERENCES Frames(Id),
	Quantity INT NOT NULL,
	OrderId INT FOREIGN KEY REFERENCES Orders(Id),
	CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
	UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE Config
(
	Id INT PRIMARY KEY IDENTITY,
	[Image] VARCHAR(255),
	[Key] VARCHAR(255) NOT NULL,
	Data VARCHAR(255) DEFAULT NULL,
	Link TEXT DEFAULT NULL,
	[Status] TINYINT,
);
CREATE TABLE Role
(
	Id INT PRIMARY KEY IDENTITY,
	Name VARCHAR(255) NOT NULL,
	[Permissions] TEXT NOT NULL,
);
CREATE TABLE Users
(
	Id INT PRIMARY KEY IDENTITY,
	Name NVARCHAR(255) NOT NULL,
	Email VARCHAR(255) NOT NULL,
	Password VARCHAR(255) NOT NULL,
	RememberToken VARCHAR(100) DEFAULT NULL,
);
CREATE TABLE UserRole 
(
	UserId INT PRIMARY KEY FOREIGN KEY REFERENCES Users(Id),
	RoleId INT FOREIGN KEY REFERENCES Role(Id)
);